package ru.kino.dev.ffi

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.json.Json
import org.junit.Test
import java.io.File

/**
 * Both sides of the boundary spell every command name, and only one of them has a compiler checking it:
 * in Rust a name without a branch does not build, here a typo builds perfectly and fails on a device.
 *
 * So the names are compared against the file Rust writes - `rust/pass-ffi/contract/commands.json`,
 * regenerated by its own test with UPDATE_CONTRACT=1. Adding a command to one side and not the other
 * fails here.
 */
class FfiCommandsTest {

    @Test
    fun `the names known here are the names the bridge answers`() {
        val fromContract: Set<String> = Json
            .decodeFromString(ListSerializer(String.serializer()), contractFile().readText())
            .toSet()

        assertEquals(fromContract, FfiCommands.ALL)
    }

    @Test
    fun `a command name is snake case, because that is what the dispatcher matches`() {
        FfiCommands.ALL.forEach { name ->
            assertTrue("'$name' is not snake_case", name.matches(Regex("[a-z][a-z0-9_]*")))
        }
    }

    // The test runs with the module directory as its working directory, but that is a Gradle detail
    // rather than a promise, so the repository root is found by looking for the crate itself
    private fun contractFile(): File {
        var directory: File? = File(".").absoluteFile
        while (directory != null) {
            val contract = File(directory, "rust/pass-ffi/contract/commands.json")
            if (contract.isFile) return contract
            directory = directory.parentFile
        }
        error("rust/pass-ffi/contract/commands.json was not found above ${File(".").absolutePath}")
    }
}
